name: test_ordo
description: "A new Flutter project for Ordo Test"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  data_channel: ^2.0.0+1
  dotted_line: ^3.2.2
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  timelines: ^0.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

flutter_gen:
  output: lib/presentation/components/gen
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/color.xml
